cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: '2024.12'
  ai_chat_mode: none
  ai_image_mode: none
  author_name: Shayne Sivley
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: kamal
  description: Vendor account, contact and product tracking with project management
    and scheduling
  docker_setup: default
  domain_name: localhost:8000
  email: shayne@fennon.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: greaselovely
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: Home Project and Vendor Management
  project_slug: domesticsentinel
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_auth: n
  use_api_keys: n
  use_async_example: n
  use_cloud_media_storage: n
  use_dark_mode: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: n
  use_health_checks: n
  use_impersonation: y
  use_sentry: n
  use_shadcn: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
