# Generated by Django 5.0 on 2023-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_provider', models.CharField(blank=True, max_length=100)),
                ('electric_provider', models.CharField(blank=True, max_length=100)),
                ('water_provider', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
