# Generated by Django 5.0 on 2023-12-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipmenttype_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_details', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Planning'), ('I', 'In Progress'), ('C', 'Completed')], max_length=10)),
                ('associated_vendors', models.ManyToManyField(blank=True, to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('first_purchase_date', models.DateField()),
                ('urls', models.JSONField(default=list)),
                ('product_image', models.ImageField(blank=True, upload_to='inventory_images/')),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('tags', models.ManyToManyField(blank=True, to='app.tag')),
            ],
        ),
    ]
