# Generated by Django 5.0.6 on 2024-06-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_houseproject_remove_vendor_address_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcontact',
            options={'verbose_name_plural': 'Vendor Contacts'},
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
